# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # VM settings
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "vagrant-test-1"

  # Network
  config.vm.network "private_network", ip: "10.1.1.5", hostname: true

  # Shared folder
  config.vm.synced_folder "./data", "/vagrant_data"

  # Provider configuration
  config.vm.provider "virtualbox" do |vb|
    # Set VM name
    vb.name = "vagrant-test-1"
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

end
