# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.hostmanager.enabled = false
  config.hostmanager.manage_host = true

  # define base hostname for the VMs without their number
  hostname_base = "personal-test-web"

  # Loop to define x amount of nodes
  (1..2).each do |node_num|

    # define full hostname with number
    hostname_full = hostname_base + "#{node_num}"

    # Define current node
    config.vm.define hostname_full do |node|
      
      # VM settings
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = hostname_full

      # Network
      node.vm.network "private_network", ip: "10.1.1.#{4+node_num}", hostname: true

      # Shared folder
      node.vm.synced_folder "./data", "/vagrant_data"

      # SSH key for Ansible
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

      node.vm.provision :hostmanager

      # Provider configuration
      node.vm.provider "virtualbox" do |vb|
        # Set VM name
        vb.name = hostname_full
        # Customize the amount of memory on the VM:
        vb.memory = "2048"
        
      end

    end

  end

end
