# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Loop to define x amount of nodes
  (1..2).each do |node_num|

    # Define current node
    config.vm.define "vagrant-test-#{node_num}" do |node|
      
      # VM settings
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "vagrant-test-#{node_num}"

      # Network
      node.vm.network "private_network", ip: "10.1.1.#{4+node_num}", hostname: true

      # Shared folder
      node.vm.synced_folder "./data", "/vagrant_data"

      # SSH key for Ansible
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

      # Provider configuration
      node.vm.provider "virtualbox" do |vb|
        # Set VM name
        vb.name = "vagrant-test-#{node_num}"
        # Customize the amount of memory on the VM:
        vb.memory = "2048"
        
      end

    end

  end

end
