---
- name: install nginx and php-fpm
  package:
    update_cache: yes
    name:
      - nginx
      - php-fpm
    state: present
- name: copy default index file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify:
  - restart nginx
...