---
- hosts: all
  become: yes
  tasks:
    - name: install updates
      package:
        update_cache: yes
        upgrade: dist

- hosts: databaseservers
  become: yes
  roles:
    - databaseserver

- hosts: webservers
  become: yes
  roles:
    - webserver

- hosts: loadbalancers
  become: yes
  roles:
    - loadbalancer
...