---
- hosts: all
  become: yes
  tasks:
    - name: test connectivity
      ping:
    - name: ensure vim is installed
      package:
        update_cache: yes
        name: vim
        state: present
...