---
- name: install haproxy
  package:
    update_cache: yes
    name:
      - haproxy
    state: present

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify:
  - restart haproxy
...